# Generated by Django 4.2.13 on 2026-03-30 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('asset_type', models.CharField(default='Web App', max_length=50)),
                ('ipv4', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv6', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('owner', models.CharField(default='PNB', max_length=100)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('port_443_open', models.BooleanField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('result_summary', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('tls_version', models.CharField(blank=True, max_length=20)),
                ('cipher_suite', models.CharField(blank=True, max_length=200)),
                ('cipher_bits', models.IntegerField(blank=True, null=True)),
                ('key_exchange', models.CharField(blank=True, max_length=100)),
                ('forward_secrecy', models.BooleanField(null=True)),
                ('is_aead_cipher', models.BooleanField(null=True)),
                ('is_weak_cipher', models.BooleanField(null=True)),
                ('cert_subject', models.CharField(blank=True, max_length=500)),
                ('cert_subject_dn', models.TextField(blank=True)),
                ('cert_issuer', models.CharField(blank=True, max_length=500)),
                ('cert_issuer_dn', models.TextField(blank=True)),
                ('cert_not_before', models.CharField(blank=True, max_length=50)),
                ('cert_not_after', models.CharField(blank=True, max_length=50)),
                ('cert_days_remaining', models.IntegerField(blank=True, null=True)),
                ('cert_sig_algorithm', models.CharField(blank=True, max_length=200)),
                ('cert_sig_oid', models.CharField(blank=True, max_length=100)),
                ('cert_key_size', models.IntegerField(blank=True, null=True)),
                ('cert_key_type', models.CharField(blank=True, max_length=50)),
                ('cert_sha1_fp', models.CharField(blank=True, max_length=200)),
                ('cert_sha256_fp', models.CharField(blank=True, max_length=200)),
                ('cert_san', models.TextField(blank=True)),
                ('cert_verified', models.BooleanField(default=True)),
                ('quantum_score', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('is_pqc_algorithm', models.BooleanField(default=False)),
                ('dimension_scores', models.TextField(blank=True)),
                ('vulnerabilities', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('hndl_risk', models.CharField(blank=True, max_length=20)),
                ('hndl_explanation', models.TextField(blank=True)),
                ('cbom_json', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scanned_by', models.CharField(default='system', max_length=100)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('targets', models.TextField()),
                ('frequency', models.CharField(default='daily', max_length=20)),
                ('cron_hour', models.IntegerField(default=2)),
                ('cron_minute', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('checker', 'Checker'), ('auditor', 'Auditor')], default='auditor', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
